Feature/axon kotlin test
AxonFramework/extension-kotlin pull request #73
Opened 2020-10-19 10:11 UTC by zambrovski

2020-10-30 09:18 UTC, sandjelkovic requested changes
The package name should be changed to indicate that these are test utilities and differentiate from the regular extension methods. Appending `.test` to the package should be enough, as there's no need to split aggregate and saga utilities for now. 
We can always segregate it in the future if there's the need for it. 

Otherwise, looks good to me 👍

2020-11-18 11:35 UTC, sandjelkovic approved these changes

2020-11-26 09:14 UTC, smcvb approved these changes
Looks good to me :+1:

2020-11-26 09:14 UTC, merged

2020-12-10 19:04 UTC, Arnaud-J reviewed
Hi!

After trying this code locally for my project, I had trouble using the defined functions. **I am still very new to Kotlin, therefore I might be missing something**.  
Nonetheless, here are some comments on how I would refactor this code. Please tell me if I am on the wrong path.

2020-12-15 13:22 UTC, sandjelkovic commented on kotlin-test/src/main/kotlin/org/axonframework/extension/kotlin/test/FixtureExtensions.kt
> +inline fun <reified T : Any> AggregateTestFixture<T>.aggregateTestFixture() =
Hey Arnaud,

Thank you for noticing this! You are completely correct, these are supposed to be factory methods for fixtures (Aggregate and Saga fixtures)

I've created an issue to handle this, you can find it here https://github.com/AxonFramework/extension-kotlin/issues/92

If you are up for it, a PR would be most welcome

2020-12-15 14:55 UTC, Arnaud-J commented on kotlin-test/src/main/kotlin/org/axonframework/extension/kotlin/test/FixtureExtensions.kt
> +inline fun <reified T : Any> AggregateTestFixture<T>.aggregateTestFixture() =
Associated PR: https://github.com/AxonFramework/extension-kotlin/pull/93

2020-12-16 08:34 UTC, sandjelkovic commented on kotlin-test/src/main/kotlin/org/axonframework/extension/kotlin/test/FixtureExtensions.kt
> +fun <T : Any> AggregateTestFixture<T>.whenever(command: Any): ResultValidator<T> = this.`when`(command)
Hey Arnaud, 

Yes, this change also makes perfect sense. Just please make sure both Aggregate and Saga fixtures are covered, both in cleaning up and example (test) usage, same as for aggregate factories.