adding Scatter Gather queries extensions
AxonFramework/extension-kotlin pull request #76
Opened 2020-10-23 04:05 UTC by hsenasilva

Hi!
This pull request should resolve this issue https://github.com/AxonFramework/extension-kotlin/issues/16

Thanks

2020-10-25 16:59 UTC, zambrovski requested changes
Please add `@since 0.2.0` annotation to KDoc of the functions.

2020-10-26 16:09 UTC, hsenasilva commented
> Please add `@since 0.2.0` annotation to KDoc of the functions.

Hi!
done

2020-10-27 20:47 UTC, hsenasilva commented
Hi @smcvb, @zambrovski any more changes in this pull request?

2020-10-29 09:38 UTC, smcvb commented
Although I know the original issue talked about using [Kotlin.time Duration](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/-duration/), I feel the mix of this extension being experimental, in combination with the Kotlin's duration to (still) be experimental to make the use case of these methods a little to low.

Hence I'd opt to move to the `scatterGather` default of `long`/`TimeUnit`, or potentially Java's `Duration`, at least for this PR.
I feel that enhances the usability of your PR for the time being. Added, _as_ the Kotlin Extension is also still experimental, we are free to change it to Kotlin's Duration once it no longer is experimental.

So, let us know what you think @hsenasilva. If you agree, please adjust your PR slightly. After that I'll have a further go at reviewing. :-)

2020-10-29 16:33 UTC, hsenasilva commented
> Although I know the original issue talked about using [Kotlin.time Duration](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/-duration/), I feel the mix of this extension being experimental, in combination with the Kotlin's duration to (still) be experimental to make the use case of these methods a little to low.
> 
> Hence I'd opt to move to the `scatterGather` default of `long`/`TimeUnit`, or potentially Java's `Duration`, at least for this PR.
> I feel that enhances the usability of your PR for the time being. Added, _as_ the Kotlin Extension is also still experimental, we are free to change it to Kotlin's Duration once it no longer is experimental.
> 
> So, let us know what you think @hsenasilva. If you agree, please adjust your PR slightly. After that I'll have a further go at reviewing. :-)

Hi @smcvb, 
It was a good point of view, i really understand that ExperimentalTime may be a blocker to someone use these functions.
I changed the PR, could you review? 
Thank you

2020-10-30 09:47 UTC, sandjelkovic requested changes
Hi  @hsenasilva, thanks for the update! Since the original issue is a bit older, I forgot to update its description, both for text and method names. That's my bad.

In the meantime, we changed collection-based methods to conform to `Many` naming instead of `Multiple`, to match the method names in another (reactor) extension. In addition, we removed `For` and `Single` from method names.

I have now updated the original issue with new information, both for Kotlin time and Multiple/Many and Single method names.

So if you could rename methods, that would be perfect. Other than that, the PR looks good!

2020-10-30 09:47 UTC, sandjelkovic commented on kotlin/src/main/kotlin/org/axonframework/extensions/kotlin/QueryGatewayExtensions.kt
> +inline fun <reified R, reified Q> QueryGateway.scatterGatherForSingle(queryName: String, query: Q, timeout: Long,
The new convention is `scatterGather` without `ForSingle`

2020-10-30 09:47 UTC, sandjelkovic commented on kotlin/src/main/kotlin/org/axonframework/extensions/kotlin/QueryGatewayExtensions.kt
> +inline fun <reified R, reified Q> QueryGateway.scatterGatherForMultiple(query: Q, timeout: Long,
The new convention is `scatterGatherMany`, without `For` and `Many` instead of `Multiple`

2020-10-30 09:47 UTC, sandjelkovic commented on kotlin/src/main/kotlin/org/axonframework/extensions/kotlin/QueryGatewayExtensions.kt
> +inline fun <reified R, reified Q> QueryGateway.scatterGatherForSingle(query: Q, timeout: Long,
The new convention is `scatterGather` without `ForSingle`

2020-10-30 09:47 UTC, sandjelkovic commented on kotlin/src/main/kotlin/org/axonframework/extensions/kotlin/QueryGatewayExtensions.kt
> +inline fun <reified R, reified Q> QueryGateway.scatterGatherForMultiple(queryName: String, query: Q, timeout: Long,
The new convention is `scatterGatherMany`, without `For` and `Many` instead of `Multiple`

2020-10-30 09:47 UTC, sandjelkovic commented on kotlin/src/main/kotlin/org/axonframework/extensions/kotlin/QueryGatewayExtensions.kt
> +inline fun <reified R, reified Q> QueryGateway.scatterGatherForOptional(query: Q, timeout: Long,
The new convention is `scatterGatherOptional` without `For`

2020-10-30 09:47 UTC, sandjelkovic commented on kotlin/src/main/kotlin/org/axonframework/extensions/kotlin/QueryGatewayExtensions.kt
> +inline fun <reified R, reified Q> QueryGateway.scatterGatherForOptional(queryName: String, query: Q, timeout: Long,
The new convention is `scatterGatherOptional` without `For`

2021-01-22 12:36 UTC, sandjelkovic approved these changes
Looks good to me 👍

2021-01-22 14:05 UTC, smcvb approved these changes
Looks good to me :+1:

2021-01-22 14:06 UTC, smcvb commented
Let's ignore the slack authorization issue of the time being...I trust @hsenasilva provided something which works.
And if it doesn't, we'll fix it afterwards.

2021-01-22 14:06 UTC, merged