Expect KClass exception in tests
AxonFramework/extension-kotlin pull request #90
Opened 2020-12-11 09:41 UTC by Arnaud-J

This follows up #67 (and the associated PR #73) and changes the way to expect exception in tests.

The current behaviour is:
```
fixture
//    .given(...)
//    .whenever(...)
    .expectException(MyException::class.java)
```

This commit make it possible to use a KClass instead of a Java class:
```
fixture
//    .given(...)
//    .whenever(...)
    .expectException(MyException::class) // <-- change here, no .java
```

This version looks more straightforward and readable to me. What do you think ?

2020-12-14 10:55 UTC, smcvb requested changes
Definitely think this makes sense, but I do think a test would be required even though it will likely only show what using looks like.

2020-12-14 16:04 UTC, Arnaud-J commented
@smcvb Added a test. Like you said, it shows the function usage, I don't see any other relevant test.

2020-12-15 11:42 UTC, smcvb approved these changes
Looks good to me :+1:
What do you think @sandjelkovic?

2020-12-15 13:04 UTC, sandjelkovic approved these changes
Everything looks good 👍

2020-12-15 13:09 UTC, merged